### ISSUE TITLE
Nvme ssd reporting back as SCSI

### ISSUE THREAD

**Issue by MitchellTrivision** [SAGSA/SystemInfo#2]
I have a system with an nvme ssd and when i use hddsmart it reports i as scsi

**Comment by SAGSA** [comment]
Unfortunately Win32_DiskDrive reports SCSI instead of NVME. I can use the MSFT_Disk class but it is only available on windows 8.1 and older systems. Perhaps when I have time I will implement it.

**Comment by SAGSA** [comment]
fixed in version 1.2.9
